config/routes.rb
Ledger::Application.routes.draw do
  

  resources :tables do
    resources :table_records, as: 'records'
  end

  

end

app/models/table.rb
class Table < ActiveRecord::Base
  has_many :table_records
end

app/models/table_record.rb
class TableRecord < ActiveRecord::Base
  belongs_to :table
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/table_records_controller.rb
class TableRecordsController < ApplicationController
  before_action :set_table_record, only: [:show, :edit, :update, :destroy]

  # GET /table_records
  # GET /table_records.json
  def index
    @table_records = TableRecord.all
  end

  # GET /table_records/1
  # GET /table_records/1.json
  def show
  end

  # GET /table_records/new
  def new
    @table_record = TableRecord.new
  end

  # GET /table_records/1/edit
  def edit
  end

  # POST /table_records
  # POST /table_records.json
  def create
    @table_record = TableRecord.new(table_record_params)
    @table = Table.where( :id => params[:table_id] )
    @table_record.table = @table
    
    respond_to do |format|
      if @table_record.save
        format.html { redirect_to @table_record, notice: 'Table record was successfully created.' }
        format.json { render action: 'show', status: :created, location: @table_record }
      else
        format.html { render action: 'new' }
        format.json { render json: @table_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /table_records/1
  # PATCH/PUT /table_records/1.json
  def update
    respond_to do |format|
      if @table_record.update(table_record_params)
        format.html { redirect_to @table_record, notice: 'Table record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @table_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /table_records/1
  # DELETE /table_records/1.json
  def destroy
    @table_record.destroy
    respond_to do |format|
      format.html { redirect_to table_records_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table_record
      @table_record = TableRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def table_record_params
      params.require(:table_record).permit(:date, :description, :value)
    end
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :set_table, only: [:show, :edit, :update, :destroy]

  # GET /tables
  # GET /tables.json
  def index
    @tables = Table.all
  end

  # GET /tables/1
  # GET /tables/1.json
  def show
  end

  # GET /tables/new
  def new
    @table = Table.new
  end

  # GET /tables/1/edit
  def edit
  end

  # POST /tables
  # POST /tables.json
  def create
    @table = Table.new(table_params)

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, notice: 'Table was successfully created.' }
        format.json { render action: 'show', status: :created, location: @table }
      else
        format.html { render action: 'new' }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tables/1
  # PATCH/PUT /tables/1.json
  def update
    respond_to do |format|
      if @table.update(table_params)
        format.html { redirect_to @table, notice: 'Table was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1
  # DELETE /tables/1.json
  def destroy
    @table.destroy
    respond_to do |format|
      format.html { redirect_to tables_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table
      @table = Table.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def table_params
      params.require(:table).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/table_records_helper.rb
module TableRecordsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Ledger"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"



  body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          a.btn.btn-navbar data-target=".nav-collapse" data-toggle="collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.brand href="#"Ledger
          .container.nav-collapse
            ul.nav
              li= link_to "Link 1", "/path1"
              li= link_to "Link 2", "/path2"
              li= link_to "Link 3", "/path3"

    .container
      .row
        .span9
          = bootstrap_flash
          = yield
        .span3
          .well.sidebar-nav
            h3 Sidebar
            ul.nav.nav-list
              li.nav-header Sidebar
              li= link_to "Link 1", "/path1"
              li= link_to "Link 2", "/path2"
              li= link_to "Link 3", "/path3"
    
      footer
        p &copy; Company 2013

app/views/table_records/_form.html.erb
<%= form_for(@table_record) do |f| %>
  <% if @table_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@table_record.errors.count, "error") %> prohibited this table_record from being saved:</h2>

      <ul>
      <% @table_record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/table_records/edit.html.erb
<h1>Editing table_record</h1>

<%= render 'form' %>

<%= link_to 'Show', @table_record %> |
<%= link_to 'Back', table_records_path %>

app/views/table_records/index.html.erb
<h1>Listing table_records</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Description</th>
      <th>Value</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @table_records.each do |table_record| %>
      <tr>
        <td><%= table_record.date %></td>
        <td><%= table_record.description %></td>
        <td><%= table_record.value %></td>
        <td><%= link_to 'Show', table_record %></td>
        <td><%= link_to 'Edit', edit_table_record_path(table_record) %></td>
        <td><%= link_to 'Destroy', table_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Table record', new_table_record_path %>

app/views/table_records/new.html.erb
<h1>New table_record</h1>

<%= render 'form' %>

<%= link_to 'Back', table_records_path %>

app/views/table_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @table_record.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @table_record.description %>
</p>

<p>
  <strong>Value:</strong>
  <%= @table_record.value %>
</p>

<%= link_to 'Edit', edit_table_record_path(@table_record) %> |
<%= link_to 'Back', table_records_path %>

app/views/tables/_form.html.erb
<%= form_for(@table) do |f| %>
  <% if @table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@table.errors.count, "error") %> prohibited this table from being saved:</h2>

      <ul>
      <% @table.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tables/edit.html.erb
<h1>Editing table</h1>

<%= render 'form' %>

<%= link_to 'Show', @table %> |
<%= link_to 'Back', tables_path %>

app/views/tables/index.html.erb
<h1>Listing tables</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tables.each do |table| %>
      <tr>
        <td><%= table.name %></td>
        <td><%= table.description %></td>
        <td><%= link_to 'Show', table %></td>
        <td><%= link_to 'Edit', edit_table_path(table) %></td>
        <td><%= link_to 'Destroy', table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Table', new_table_path %>

app/views/tables/new.html.erb
<h1>New table</h1>

<%= render 'form' %>

<%= link_to 'Back', tables_path %>

app/views/tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @table.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @table.description %>
</p>

<%= link_to 'Edit', edit_table_path(@table) %> |
<%= link_to 'Back', tables_path %>